# Generated by Django 2.2.7 on 2019-12-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cl',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
